### ISSUE TITLE
请问支持docker一键部署么

### ISSUE THREAD

**Issue by MrRohwei** [clklog/clklog#1]
官网没看到有docker一键部署，请问有计划支持么

**Comment by pongpongcn** [comment]
It's on road~
We are working on building docker image of each ClkLog components.
After that, we can have docker compose files, and K8s deployment files.

Thanks for your interesting.

**Comment by evawyue** [comment]
你好，clklog现在已经支持docker一键部署了，详细内容请参考：https://clklog.com/#/quickstart/docker-installation，谢谢！

**Comment by evawyue** [comment]
this issues is finished!
